[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
runOnSave = true

[ui]
hideSidebarNav = true

[layout]
# 设置页面宽度
maxWidth = "1400px"
